using System;
/*
namespace com.gigagoga.storage.meta
{
    [Flags]
    public enum StorableFieldInfo : int
    {
        Default = 0,
        PrimaryKey = 1,
        AutoGenerated = 2,

        ReadOnly = 4,

        Nullable = 8,
        Optional = 16,
        Index = 32,
        Unique = 64,
        AutoIncrement = 128,
        Randomized = 256
    }
}
*/