using System;
using com.gigagoga.storage.meta;

namespace com.gigagoga.storage
{
    public abstract class StorableObject : StorableBase
    {

        [Storable("id", StorableDataType.AutoIdentity, StorableInfo.AutoGenerated | StorableInfo.AutoIncrement | StorableInfo.PrimaryKey | StorableInfo.ReadOnly)]
        protected Int64 id;

        public override Int64 ID
        {
            get
            {
                return this.id;
            }
            set
            {
                if (this.id == 0)
                {
                    this.id = value;
                }
            }
        }

        public static bool IsNullOrEmpty(StorableObject obj)
        {
            return (obj == null || obj.id == 0);
        }

        /*
        protected StorableObjectState state = StorableObjectState.None;
        public override StorableObjectState State
        {
            get
            {
                return this.state;
            }
            set
            {
                this.state = value;
            }
        }
        */
    }
}
